project:
  type: website
  output-dir: docs

website:
  title: "Tropical forest degradation and regeneration"
  navbar:
    right:
      - href: index.qmd
        text: Interactive map
      - about.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

